# Generated by Django 3.2.10 on 2021-12-18 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfoliovalue_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliovalue',
            name='date_added',
            field=models.DateField(),
        ),
    ]
